import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/Sidebar";
import { Navbar } from "@/components/Navbar";
import { ToastProvider } from '@/components/ui/use-toast';
import { TourProvider } from '@/components/tours/TourProvider';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-background antialiased dark">
      <body className={`${geistSans.variable} ${geistMono.variable} h-full overflow-hidden flex`}>
        <ToastProvider>
          <TourProvider>
            <Sidebar />
            <main className="flex flex-col flex-1 h-full overflow-hidden bg-muted/20">
              <Navbar />
              <div className="flex-1 overflow-y-auto p-6">
                {children}
              </div>
            </main>
          </TourProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
