import { Injectable, Logger } from '@nestjs/common';
import { AiProvider } from './ai.interface';

@Injectable()
export class MockAiProvider implements AiProvider {
    private readonly logger = new Logger(MockAiProvider.name);

    async analyzeRequirement(content: string) {
        this.logger.log('Mock AI analyzing requirement');
        const score = content.length > 50 ? 85 : 40;
        return {
            score,
            clarity: 80,
            completeness: score,
            testability: 90,
            consistency: 85,
            feedback: score < 50 ? ['Description too short', 'Lack of acceptance criteria'] : ['Good quality'],
        };
    }

    async triageBug(bugValues: { title: string; description: string }) {
        this.logger.log('Mock AI triaging bug');
        const isCritical = bugValues.title.toLowerCase().includes('crash');
        return {
            suggestedSeverity: bugValues.title.toLowerCase().includes('crash') ? 'CRITICAL' : 'MEDIUM',
            suggestedPriority: bugValues.title.toLowerCase().includes('crash') ? 'P0' : 'P2',
            duplicateCandidates: [],
            rootCauseHypothesis: "Based on the description, this looks like a potential null pointer exception in the render loop.",
        };
    }

    async generateTestCode(testCase: { title: string; steps: any[] }, framework: string): Promise<string> {
        return `
import { test, expect } from '@playwright/test';

test('${testCase.title}', async ({ page }) => {
    // Generated by QANexus AI
    // Steps:
    ${testCase.steps.map(s => `// - ${s.step} (Expect: ${s.expected})`).join('\n    ')}
    
    await page.goto('/');
    // TODO: Implement specific selectors
});
`;
    }
}
