import { Injectable, Inject, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { AutomationCandidate, CandidateStatus } from './automation-candidate.entity';
import { AutomationRun, RunStatus } from './automation-run.entity';
import { TestAutomationSettingsService } from './test-automation-settings.service';
import { GitIntegrationService } from './git-integration.service';
import { TestCase } from '../test-keys/test-case.entity';
import { AiProvider, AI_PROVIDER_TOKEN } from '../ai/ai.interface';

@Injectable()
export class TestAutomationService {
    constructor(
        @InjectRepository(AutomationCandidate)
        private candidateRepo: Repository<AutomationCandidate>,
        @InjectRepository(AutomationRun)
        private runRepo: Repository<AutomationRun>,
        @InjectRepository(TestCase)
        private testCaseRepo: Repository<TestCase>,
        private settingsService: TestAutomationSettingsService,
        private gitService: GitIntegrationService,
        @Inject(AI_PROVIDER_TOKEN) private aiProvider: AiProvider,
    ) { }

    async generatePr(tenantId: string, projectId: string, candidateId: string) {
        // 1. Fetch Context
        const candidate = await this.candidateRepo.findOneBy({ id: candidateId });
        if (!candidate) throw new NotFoundException('Candidate not found');

        const testCase = await this.testCaseRepo.findOneBy({ id: candidate.testCaseId });
        if (!testCase) throw new NotFoundException('Test Case not found');

        const settings = await this.settingsService.getSettings(tenantId, projectId);
        if (!settings.enabled) throw new Error('Automation is disabled for this project');

        // 2. Generate Code
        const code = await this.aiProvider.generateTestCode({
            title: testCase.title,
            steps: testCase.steps || []
        }, settings.framework);

        // 3. Git Operations
        const branchName = \`tg/auto-tests/TEST-\${testCase.id.substring(0, 8)}\`;
        const filePath = \`\${settings.testRootPath}/auto-\${testCase.id.substring(0, 8)}.spec.ts\`;

        await this.gitService.createBranch(settings.automationRepoOwner, settings.automationRepoName, branchName);
        await this.gitService.commitFile(settings.automationRepoOwner, settings.automationRepoName, branchName, filePath, code, \`Add automated test for \${testCase.title}\`);
        
        const pr = await this.gitService.createPullRequest(
            settings.automationRepoOwner, 
            settings.automationRepoName, 
            branchName, 
            \`feat: Automate \${testCase.title}\`, 
            \`Generated by QANexus for Test Case: \${testCase.title}\`
        );

        // 4. Update Records
        const run = this.runRepo.create({
            candidateId,
            tenantId,
            status: RunStatus.PR_CREATED,
            generatedSnippetPath: filePath,
            githubPrUrl: pr.url
        });
        await this.runRepo.save(run);

        candidate.status = CandidateStatus.PR_OPEN;
        await this.candidateRepo.save(candidate);

        return { prUrl: pr.url };
    }
}
